openapi: 3.0.0
info:
  title: Problem Details
  description: |
    This is a collection of [Problem Details](https://www.rfc-editor.org/rfc/rfc7807)
  version: 0.1.0-dev
servers: []
paths: {}
components:
  responses:
    ProblemResponse:
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Problem"
      description: A generic problem
  schemas:
    Problem:
      description: A Problem object
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |
            A URI reference that identifies the
            problem type.  This specification encourages that, when
            dereferenced, it provide human-readable documentation for the
            problem type (e.g., using HTML).  When this member is not present, 
            its value is assumed to be "about:blank"
          default: about:blank
        title:
          type: string
          description: |
            A short, human-readable summary of the problem
            type.  It SHOULD NOT change from occurrence to occurrence of the
            problem, except for purposes of localization (e.g., using
            proactive content negotiation)
          example: Service Unavailable
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this 
            occurrence of the problem
          minimum: 400
          maximum: 599
          example: 503
    ProblemDetail:
      description: A Problem Details object
      type: object
      allOf:
      - $ref: "#/components/schemas/Problem"
      properties:
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
          example: The server is currently not avaliable.
